services:
  - type: web
    name: deepfake-detector
    env: python
    buildCommand: bash render-build.sh
    startCommand: gunicorn app:app --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16